# Generated by Django 3.2.20 on 2023-08-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='seller',
        ),
    ]
