# Generated by Django 5.2.1 on 2025-05-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuctionItem',
        ),
    ]
