# Generated by Django 3.2.20 on 2023-08-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20230817_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(default='active', max_length=64),
        ),
    ]
